language: objective-c
osx_image: xcode10.0
cache: cocoapods
podfile: Podfile
before_install:
    # - gem install cocoapods # Since Travis is not always on latest version
    - pod repo update
    - pod install
script:
    ./travis.sh
