platform :ios, "9.0"
#inhibit_all_warnings!
use_frameworks!

target "MealDock" do
    pod 'Alamofire', '~> 4.7'
    pod 'DJKFlatIconAuthors', :git => 'https://github.com/WataruSuzuki/DJKFlatIconAuthors.git'
    pod 'DJKUtilities', :git => 'https://github.com/WataruSuzuki/DJKUtilities.git'
    # pod 'DJKUtilAdMob', :git => 'https://github.com/WataruSuzuki/DJKUtilAdMob.git'#, :configuration => ["Release"]
    pod 'DJKInAppPurchase', :git => 'https://github.com/WataruSuzuki/DJKInAppPurchase.git'#, :configuration => ["Release"]
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/AdMob'
    # pod 'BubbleTransition-objc'
    # pod 'RMPZoomTransitionAnimator'
    pod 'PersonalizedAdConsent'
    # pod 'ZFDragableModalTransition'
    pod 'GoogleMobileAdsMediationNend'
end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-MealDock/Pods-MealDock-acknowledgements.plist', 'MealDock/Settings.bundle/Pods-acknowledgements.plist')
end
