# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Tests"
    lane :tests do
    run_tests(
        workspace: "MealDock.xcworkspace",
        scheme: "MealDock",
        devices: [
            # "iPhone 6 (10.3.1)",
            # "iPad Air (9.3)",
            # "iPhone 7 Plus (10.3.1)",
            # "iPad Pro (12.9 inch) (10.3.1)",
            # "iPhone X (11.4)",
            # "iPad Pro (10.5-inch) (11.4)",
            "iPhone XS Max",
            "iPad Pro (12.9-inch) (3rd generation)"
        ],
        disable_concurrent_testing: true,
        configuration: 'UnitTesting'
    )
    end
    desc "Push a new beta build to TestFlight"
    lane :beta do
        build_app(workspace: "MealDock.xcworkspace", scheme: "MealDock")
        upload_to_testflight
    end
end
